/*
 * Copyright © 2025-2026 Metreeca srl
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * RFC 7807 problem details for HTTP APIs.
 *
 * Provides the {@link Problem} type for structured, machine-readable error information in HTTP responses
 * and a guarded {@link createFetch} wrapper with consistent promise semantics.
 *
 * **Problem Details**
 *
 * ```typescript
 * import { Problem } from "@metreeca/core/problem";
 *
 * const problem: Problem = {
 *   status: 404,
 *   title: "Not Found",
 *   detail: "Resource /api/users/123 does not exist",
 *   instance: "/api/users/123",
 *   report: { timestamp: "2025-12-02T10:30:00Z" }
 * };
 * ```
 *
 * **Guarded Fetch**
 *
 * ```typescript
 * import { createFetch } from "@metreeca/core/problem";
 *
 * const guard = createFetch(fetch);
 *
 * try {
 *   const response = await guard("https://api.example.com/data");
 *   // response.ok is guaranteed true
 * } catch (problem) {
 *   // problem is a Problem with parsed error details
 *   console.error(problem.status, problem.detail, problem.report);
 * }
 * ```
 *
 * @module
 *
 * @see {@link https://datatracker.ietf.org/doc/html/rfc7807 RFC 7807 - Problem Details for HTTP APIs}
 */

import { immutable } from "../common/deep.js";
import type { Value } from "../index.js";


/**
 * Problem Details for HTTP APIs.
 *
 * Standardized format for machine-readable error information in HTTP responses, as defined by RFC 7807.
 * All fields are optional, allowing flexibility in error reporting. Use `detail` for human-readable
 * occurrence-specific information, and `report` for machine-readable data.
 *
 * @see {@link https://datatracker.ietf.org/doc/html/rfc7807 RFC 7807 - Problem Details for HTTP APIs}
 */
export interface Problem {

	/**
	 * Short, human-readable summary of the problem type.
	 *
	 * Should be the same for all occurrences of this problem type (e.g., "Payment Required", "Not Found").
	 */
	readonly title?: string;

	/**
	 * URI reference identifying the problem type.
	 *
	 * @defaultValue "about:blank"
	 */
	readonly type?: string;

	/**
	 * URI reference identifying the specific occurrence of the problem.
	 */
	readonly instance?: string;

	/**
	 * HTTP status code generated by the origin server.
	 */
	readonly status?: number;

	/**
	 * Human-readable explanation specific to this occurrence of the problem.
	 */
	readonly detail?: string;

	/**
	 * Machine-readable error report (extension field).
	 */
	readonly report?: Value;

}


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

/**
 * Creates a fetch function with consistent promise resolution/rejection behaviour.
 *
 * Wraps a fetch function to provide consistent, sensible promise semantics where successful responses resolve
 * and all errors reject with structured {@link Problem} exceptions:
 *
 * - **Response is `ok`** (2xx `status`): Promise resolves with the response unchanged
 * - **Response is not `ok`** (non-2xx `status`): Response body is read according to `Content-Type`, converted to
 *   {@link Problem}, and promise rejects:
 *   - `text/plain`: Response body as text in `report` field
 *   - JSON-based MIME types (e.g., `application/json`, `application/ld+json`, `application/problem+json`):
 *     Parsed JSON payload in `report` field
 *   - Other content types: `status` code and `statusText` only
 * - **Fetch exception occurs** (network errors, timeouts, CORS failures): Exception is converted to {@link Problem}
 *   with `status` 0 and promise rejects
 *
 * If response body parsing fails, promise rejects with {@link Problem} containing the original response `status`
 * and `statusText`.
 *
 * @param base The fetch function to wrap
 *
 * @returns Fetch function whose promises reject with {@link immutable} {@link Problem} exceptions for all error
 *     conditions
 */
export function createFetch(base: typeof fetch): typeof fetch {
	return (input: RequestInfo | URL, init?: RequestInit) => base(input, init)

		.catch(error => {

			throw immutable<Problem>({

				status: 0,
				detail: `fetch error <${error}>`

			});

		})

		.then(response => {

			if ( response.ok ) {

				return response;

			} else {

				const mime = response.headers.get("Content-Type");

				if ( mime?.match(/^text\/plain\b/i) ) {

					return response.text()

						.catch(_ => {

							throw immutable<Problem>({

								status: response.status,
								detail: response.statusText

							});

						})

						.then(value => {

							throw immutable<Problem>({

								status: response.status,
								detail: response.statusText,

								report: value

							});

						});

				} else if ( mime?.match(/[\/+]json\b/i) ) {

					return response.json()

						.catch(_ => {

							throw immutable<Problem>({

								status: response.status,
								detail: response.statusText

							});

						})

						.then(value => {

							throw immutable<Problem>({

								status: response.status,
								detail: response.statusText,

								report: value

							});

						});

				} else {

					throw immutable<Problem>({

						status: response.status,
						detail: response.statusText

					});

				}

			}

		});
}
