/*
 * Copyright © 2026 Metreeca srl
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Composable fetch middleware.
 *
 * Provides a composable middleware layer over the standard
 * {@link https://developer.mozilla.org/docs/Web/API/Window/fetch `fetch`} function. A {@link Middleware} wraps a
 * {@link Fetch} implementation, returning a drop-in replacement that adjusts requests and responses as they flow
 * through, and {@link createFetch} assembles a chain of middlewares into a single client to be shared across an
 * application.
 *
 * Ready-made middlewares cover recurring concerns: {@link basic} and {@link bearer} authenticate every request,
 * {@link headers} supplies default header fields, {@link throttle} paces exchanges and retries transient failures,
 * {@link success} admits only 2xx responses, reporting failed exchanges as structured {@link Problem | problem}
 * details, and {@link transport} routes exchanges through an implementation other than the standard function.
 *
 * **Usage**
 *
 * ```typescript
 * import { basic, createFetch, success } from "@metreeca/core/fetch";
 *
 * // shared across the application
 *
 * const client = createFetch(
 *   basic("user", "secret"),
 *   success()
 * );
 *
 * // rejects unless response.ok
 *
 * const response = await client("https://api.example.com/data");
 * ```
 *
 * @module
 *
 * @groupDescription Middlewares
 *
 * Ready-made middlewares to be layered over a {@link Fetch} implementation by {@link createFetch}.
 *
 * @see {@link https://fetch.spec.whatwg.org/ WHATWG Fetch Standard}
 * @see {@link https://www.rfc-editor.org/rfc/rfc9457 RFC 9457 - Problem Details for HTTP APIs}
 */

import type { Value } from "../../index.js";

export * from "./basic.js";
export * from "./bearer.js";
export * from "./headers.js";
export * from "./success.js";
export * from "./throttle.js";


/**
 * Fetch function signature.
 *
 * Types both the standard {@link https://developer.mozilla.org/docs/Web/API/Window/fetch `fetch`} function and the
 * drop-in replacements derived from it, so that wrapped clients stay interchangeable with the platform primitive.
 */
export type Fetch = typeof fetch;

/**
 * Fetch middleware.
 *
 * Wraps a {@link Fetch} implementation, returning a drop-in replacement that adjusts requests before delegating to it
 * and responses after it replies. Middlewares are layered into a client by {@link createFetch}, each seeing the
 * exchange as the layers above it left it.
 */
export type Middleware = (fetch: Fetch) => Fetch


/**
 * Problem details for HTTP APIs.
 *
 * Portable description of an error condition, as defined by RFC 9457, which obsoletes RFC 7807. Every field is
 * optional, so a report carries as much detail as its source provides: `type` and `title` classify the problem,
 * `status`, `detail`, and `instance` pin it to a specific occurrence, and `report` conveys machine-readable data
 * for automated handling.
 *
 * {@link success} reports failed exchanges in this shape, so a client assembled with it surfaces transport failures
 * and error responses alike as problem details.
 *
 * @example
 *
 * ```typescript
 * const problem: Problem = {
 *   status: 404,
 *   title: "Not Found",
 *   detail: "Resource /api/users/123 does not exist",
 *   instance: "/api/users/123",
 *   report: { timestamp: "2025-12-02T10:30:00Z" }
 * };
 * ```
 *
 * @see {@link https://www.rfc-editor.org/rfc/rfc9457 RFC 9457 - Problem Details for HTTP APIs}
 */
export type Problem = {

	/**
	 * Short, human-readable summary of the problem type.
	 *
	 * Should be the same for all occurrences of this problem type, for example `Payment Required` or `Not Found`.
	 */
	readonly title?: string;

	/**
	 * URI reference identifying the problem type.
	 *
	 * @defaultValue "about:blank"
	 */
	readonly type?: string;

	/**
	 * URI reference identifying the specific occurrence of the problem.
	 */
	readonly instance?: string;

	/**
	 * HTTP status code generated by the origin server.
	 */
	readonly status?: number;

	/**
	 * Human-readable explanation specific to this occurrence of the problem.
	 */
	readonly detail?: string;

	/**
	 * Machine-readable details about this occurrence of the problem.
	 *
	 * An RFC 9457 extension member, shaped as the reporting party requires, for instance a validation trace or a
	 * diagnostic payload consumers may branch on.
	 */
	readonly report?: Value;

}


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

/**
 * Creates a fetch client from a chain of middlewares.
 *
 * Layers `middlewares` over the standard
 * {@link https://developer.mozilla.org/docs/Web/API/Window/fetch `fetch`} function in declaration order: requests are
 * processed by the first middleware first and reach the standard function last; responses travel back through the
 * chain in reverse. An empty chain yields the standard function itself.
 *
 * The standard function is resolved when the chain is assembled, so a client routes through a global replaced before
 * its creation, such as a test double or a polyfill installed at start-up, but not through one replaced afterwards.
 * To bind a client to an implementation of its own, regardless of the global one, close the chain with
 * {@link transport}.
 *
 * @param middlewares The {@link Middleware | middlewares} to be layered over the standard `fetch` function, in request
 *     processing order
 *
 * @returns A drop-in replacement for the standard `fetch` function routing every exchange through `middlewares`
 */
export function createFetch(...middlewares: readonly Middleware[]): Fetch {

	return middlewares.reduceRight((next, middleware) => middleware(next), fetch);

}


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

/**
 * Creates a middleware routing exchanges through a given fetch implementation.
 *
 * Supplies the transport a client is to run on, for instance a proxy-bound `undici` fetch, a platform service binding,
 * or a test double, in place of the standard function {@link createFetch} would otherwise delegate to:
 *
 * ```typescript
 * const client = createFetch(basic("user", "secret"), success(), transport(custom));
 * ```
 *
 * Ignores the {@link Fetch} implementation it wraps, delegating every exchange to `fetch` instead: middlewares
 * declared before it process exchanges as usual, while middlewares declared after it are never reached, so this
 * middleware is to be declared last in a chain.
 *
 * @param fetch The {@link Fetch} implementation to route every exchange through
 *
 * @returns A {@link Middleware} delegating every exchange to `fetch`, ignoring the {@link Fetch} implementation it
 *     wraps
 *
 * @group Middlewares
 */
export function transport(fetch: Fetch): Middleware {

	return () => fetch;

}
